version: '3.8'
services:
  redis-server-twitter:
    container_name: redis-server-twitter
    image: 'redis:7.0.0'
    ports:
      - '5000:6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
